# To choose a Python version, first create the env with:
# conda create -n sparktorch python=3.6
# and then update it
# conda env update -n sparktorch -f environment.yml
name: sparktorch
channels:
- https://repo.anaconda.com/pkgs/main/linux-64/
- pytorch
dependencies:
# runtime
- six
- pandas
- h5py
- pillow
- dill
- pytorch=2.0.0
- flask
- requests
# test
- coverage
- nose
- pip:
  # test
  - yapf
  - py4j
  - pytest