name: CI

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -t local-test --build-arg PYTHON_VERSION=3.8 .
      - name: Run tests
        run: docker run --rm local-test:latest bash -i -c "pytest"